---
- hosts: localhost
  gather_facts: no
  vars:
    cvaas_url:  www.arista.io
    cvaas_api_url: apiserver.arista.io
    cvaas_api: https://{{cvaas_url}}/api/v3/services/admin.Enrollment/AddEnrollmentToken
    cvaas_token: "{{lookup('file', 'cvaas_service.tok')}}"
    cvp_url: <cvp IP/FQDN>
    cvp_device_api: "https://{{cvp_url}}/cvpservice/enroll/createToken"
    cvp_token: "{{lookup('file', 'onprem.tok')}}"
  tasks:
  - name: "Generating TerminAttr onboarding token on CVaaS instance"
    tags: [build]
    ansible.builtin.uri:
      url: "{{ cvaas_api }}"
      method: POST
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvaas_token }}"
      validate_certs: no
      return_content: yes
      body: '{"enrollmentToken": {"reenrollDevices": ["*"], "validFor": "720h"}}'
    register: cv_onboarding_token
    until: cv_onboarding_token.status == 200
    retries: 10
    delay: 2
  # Writing cvaas token to file
  - name: "Parsing CVaaS token"
    tags: [build]
    set_fact:
      cv_onboarding_token: "{{ cv_onboarding_token.content | list | join }}"
  - name: "Writing CVaaS token to file"
    tags: [build]
    copy:
      content: "{{ cv_onboarding_token[0].enrollmentToken.token }}"
      dest: "./cv-onboarding-token"
  - name: "Generating TerminAttr onboarding token on onprem instance - active"
    tags: [build]
    ansible.builtin.uri:
      url: "{{ cvp_device_api }}"
      method: POST
      headers:
        Accept: "application/json"
        Cookie: "access_token={{ cvp_token }}"
      validate_certs: no
      return_content: yes
      body: '{"reenrollDevices": ["*"], "duration": "720h"}'
    register: token
    until: token.status == 200
    retries: 10
    delay: 2
  # Writing onprem token to file
  - name: debug token
    tags: [build]
    debug: var=token
  - name: "Parsing CVP on-prem token"
    tags: [build]
    set_fact:
      token: "{{ token.content | list | join }}"
  - name: "Writing on-prem token to file"
    tags: [build]
    copy:
      content: "{{ token.data }}"
      dest: "./token"

- name: Onboard devices to CVaaS and on-prem
  hosts: all
  vars:
    ansible_user: arista
    ansible_password: arista
    ansible_connection: network_cli
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_network_os: eos
    ansible_httpapi_port: 443
    ansible_python_interpreter: $(which python3)
    terminattr_vrf: MGMT                     # Change this if TerminiAttr needs to use another VRF
  tasks:
  - name: "Copy onboarding tokens"
    tags: [copy]
    ansible.builtin.uri:
      url: "https://{{ansible_user}}:{{ansible_password}}@{{hostvars[inventory_hostname].ansible_host}}/command-api"
      method: POST
      headers:
        Accept: "application/json"
      validate_certs: no
      return_content: yes
      force_basic_auth: true
      body:
        jsonrpc: "2.0"
        method: "runCmds"
        params:
          version: 1
          cmds:
          - "enable"
          - cmd: "copy terminal: file:/tmp/token"
            input: "{{lookup('file', './token')}}"
          - cmd: "copy terminal: file:/tmp/cv-onboarding-token"
            input: "{{lookup('file', './cv-onboarding-token')}}"
          format: json
          timestamps: false
          autoComplete: false
          expandAliases: false
          stopOnError: false
          streaming: false
          includeErrorDetail: false
        id: EapiExplorer-1
      body_format: json
    register: cv_onboarding_token
    until: cv_onboarding_token.status == 200
    retries: 10
    delay: 2

  - name: restart TerminAttr
    eos_command:
      commands:
        - "enable"
        - "configure"
        - "daemon TerminAttr"
        - "exec /usr/bin/TerminAttr -cvopt cvaas.addr={{cvaas_api_url}}:443 -cvopt cvaas.vrf={{terminattr_vrf}} -cvopt cvaas.auth=token-secure,/tmp/cv-onboarding-token -cvopt onprem.addr={{cvp_url}}:9910 -cvopt onprem.vrf={{terminattr_vrf}} -cvopt onprem.auth=token,/tmp/token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs -disableaaa"
        - "shutdown"
        - "no shutdown"